// src/config/semantic/catalogIntents.ts
export const CATALOG_INTENT_PHRASES: Record<string, string[]> = {
  stock_check: [
    'is this in stock',
    'how many do you have',
    'is it available',
    'avialable',
    'do you have stock',
    'any left',
    'still available',
    'do you have more',
  ],
  sizing_inquiry: [
    'what sizes do you have',
    'does it come in small',
    'sizing information',
    'how does it fit',
    'size chart',
    'measurements',
    'what size options',
    'size guide',
    // Product-category synonyms
    'do these pants run true to size',
    'what is the size chart for trousers',
    'how do jeans sizes work',
    'what size shirt should i get',
    'do your sneakers fit normal',
    'do these shorts run big',
    'jacket sizing guide',
  ],
  product_search: [
    'looking for',
    'do you sell',
    'show me',
    'i want to buy',
    'find products',
    'browse catalog',
    'what do you have',
    'got any',
    // Product-category synonyms
    'show me some pants',
    'looking for trousers',
    'do you have jeans',
    'where are the shirts',
    'need some sneakers',
    'show me jackets',
    'browse shorts collection',
  ],
  variant_lookup: [
    'blue hoodie',
    'medium size',
    'leather jacket',
    'specific variant',
    'color options',
    'which colors',
    'in black',
    'do you have this in blue',
  ],
};